### PR TITLE
Add TypoHero

### PR DESCRIPTION
**Pull request by ddfreyne**
CC @minad @nanoc/contributors

### CODE REVIEW

**Comment by mpapis** [comment]
tests are failing - but does not look like related (yet)

**Comment by ddfreyne** [comment]
Yup, tests are failing because it didn’t have the proper Travis CI set up yet.

**Comment by mpapis** [comment]
I mean - it would be nice to see test results

**Comment by ddfreyne** [comment]
I rebased, so test results should come in soon.

**Comment by mpapis** [comment]
and the tests passed => :+1:

**Pull request merged**
