### PR TITLE
fix some listing marked as "legacy" to "new"

### PR DESCRIPTION
**Pull request by kAworu**

### CODE REVIEW

**Comment by ddfreyne** [comment]
Thanks for the patch!

The steps *are* still legacy, but they’re intermediate step. For that reason, they can’t be marked as “new”. This has confused others, too, and so I have an alternate patch which changes the wording to “legacy - intermediate” (see 236290b).

**Comment by ddfreyne** [comment]
(Other PRs: #130, #129)

**Comment by ddfreyne** [comment]
And a screenshot, for future reference:

screen shot 2016-04-22 at 23 03 59

**Comment by kAworu** [comment]
ok, thank you for the clarification. https://github.com/nanoc/nanoc.ws/commit/236290bffdd859b7da1fec4fc54556c3c29b245c looks like a good solution to me.

**Pull request closed without merging**
