### PR TITLE
Use D★Mark

### PR DESCRIPTION
**Pull request by ddfreyne**
[D★Mark](https://github.com/ddfreyne/d-mark) is a markup format for prose, designed as a more flexible alternative to Markdown, AsciiDoc, etc. The Nanoc web site uses custom markup using `span`s in Markdown, which tends to become verbose and cumbersome to deal with. This new markup language hopes to solve that.

This code has a workaround for https://github.com/ddfreyne/d-mark/issues/4. Will fix soon.

### CODE REVIEW

**Comment by DaveEveritt** [comment]
Interesting (especially the coincidentally? LATEX-like delimiters) - OOI what are the advantages over Fletcher Penney's Multimarkdown?

**Comment by ddfreyne** [comment]
@DaveEveritt I’ll elaborate on the design decisions and the raison d’être for D★Mark in the README file of the repository itself at some point, but it basically boils down to the fact that all the existing lightweight markup language (Markdown and its variants, AsciiDoc, …) are not extensible, and limit the flexibility in using semantic markup.

I’ve taken inspiration mainly from LaTeX, and also a little from Textile. The reason is that I’m working on [generating a book](https://github.com/nanoc/nanoc.ws/pull/144) based off the contents of the web site. The reason for D★Mark is also for being able to describe content in a way that makes it easier to convert to LaTeX.

**Comment by ddfreyne** [comment]
Also worth noting is that D★Mark is closer to to XML than to any of the lightweight markup languages like Markdown and Asciidoc, because it doesn’t define any semantics.

It’s also unlike JSON or YAML, because it is intended for prose. I suppose you could use it as a JSON or YAMl alternative, but it wouldn’t really be all that nice.

**Comment by ddfreyne** [comment]
Some more thoughts (I’ll use this thread as a scratchpad for inspiration for the README, I guess):

* Different Markdown implementations behave differently. A good example is 456153420374b8c8b9f9c29701040ed7a7a4e2b9 which demonstrates that Kramdown doesn’t behave the same as GitHub Flavoured Markdown. This has been a long-time frustration for me, and for many others.

* There is the need to be able to use semantic markup. Without this, formatting becomes inconsistent. For example, I’d like filenames to be formatted uniformly across the site and in the book, and I can say the same for identifiers, patterns, product names, etc.

* I would like semantic markup so that I can give it meaning beyond the styling. For instance, collecting terms to be used in an index could be done automatically using a `%firstterm{…}` element.

* With Markdown, I feel I resort to plain HTML too often. This brings a bunch of problems, such as syntax highlighting issues, and issues with Markdown formatting taking precedence over HTML (for instance, two `span`s with a `*` will trip up some Markdown processors, who’ll try to convert it into an `em`). I end up writing large parts of the text in HTML, which defeats the point of having Markdown in the first place.

* D★Mark is deliberately designed to be simple, and free of ambiguity. This makes it predictable, easy to use, easy to syntax highlight, and hopefully fast to parse, too.

* The name of D★Mark is ridiculous and I feel like I’m badly ego-tripping. I’ll probably change it.

**Comment by DaveEveritt** [comment]
Understood. Penney's Multimarkdown has some overlapping aims but isn't extensible, and is incomplete when generating LATEX via Pandoc. I'm interested because of the need for a 'universal base format' from which anything can be generated. Nothing wrong with laying claim, but if the 'D' is ego-tripping (it's not that bad!) perhaps 'TextMark'?

**Comment by ddfreyne** [comment]
> I'm interested because of the need for a 'universal base format' from which anything can be generated.

Anything can be generated from D★Mark, and that is easy, because the language doesn’t define semantics. The elements I’m using on nanoc.ws correspond to the HTM ones I was using previously, along with elements corresponding to the custom class names of `span`s.

I inspired myself on DocBook when choosing the class names (and now the element names). I suppose it would be possible to reword DocBook in a D★Mark syntax, but that’s a _ton_ of work, and I’d rather focus on what is needed for nanoc.ws. Perhaps the D★Mark dialect used for nanoc.ws could be a strict subset of DocBook.

> Nothing wrong with laying claim, but if the 'D' is ego-tripping (it's not that bad!) perhaps 'TextMark'?

I think D★Mark is growing on me. I think I’ll stick with it :)

**Comment by DaveEveritt** [comment]
I'm trying to generate a book _and_ a Nanoc website from a single set of documents, which is why I'm interested. So far, the quickest method has been LaTeX-> Markdown via Pandoc, but then hand-tweaking two sets of the same content, which defeats the purpose.

**Comment by ddfreyne** [comment]
@DaveEveritt Looks like we’re trying to achieve the same thing, then!

The process I’ve developed for nanoc.ws is obviously rather experimental—D★Mark isn’t even 24 hours old. How well this works out remains to be seen, but I’m excited and quite hopeful.

**Comment by DaveEveritt** [comment]
Indeed! I'll keep track of this, comment and perhaps try out when you think it's ready and I free up a day or two to set things up.

**Comment by chrisberkhout** [comment]
Looks interesting. You refer to it just as markup, but it seems to include features I'd usually associate with templating.

**Comment by ddfreyne** [comment]
@chrisberkhout I’m assuming you’re referring to the `note. <sudo-gem-install>` syntax. That bit is handled outside of D*Mark as a gsub-style filter for predefined content. It’s a bit of a hack, but it’s something that’s been in use before, but I’m thinking about alternatives.

You could use it to write entire layouts/templates, but you’re still stuck without a vocabulary unless you define it yourself, and at that point I’m not sure D*Mark still has an advantage.

**Comment by TheLonelyGhost** [comment]
+1 for use of the ASCII version of the name D*Mark, though it may have issues with globbing in the command line. Far less of a hurdle than UTF-8 characters in the terminal.

**Comment by chrisberkhout** [comment]
@ddfreyne Oh, yeah. Actually I had misread something... When I saw `%code[lang=ruby]{Nanoc::VERSION}` I was mostly looking at the `{Nanoc::VERSION}` part and thought that was evaluating Ruby code. So I take back that comment about templates.

**Comment by ddfreyne** [comment]
@chrisberkhout There is `%erb{…}` now, which I use for outputting small bits of dynamic data (Ruby version, last release number, etc). It’s not quite as powerful as a templating language though.

**Comment by ddfreyne** [comment]
This now uses a rewritten version of D*Mark (or D★Mark if you prefer), which should be both faster and more reliable.

The build now also passes, which is nice!

**Comment by ddfreyne** [comment]
Quick, perhaps not so meaningful performance report:

```
                          | count    min    avg    max     tot
--------------------------+-----------------------------------
[snip]
               dmark2html |    12  0.00s  0.02s  0.03s   0.18s
[snip]
```

< 20ms total to parse and format 20 pages isn’t too bad.

**Comment by ddfreyne** [comment]
All pages are now translated to D*Mark.

Speed is good:

```                          | count    min    avg    max     tot
--------------------------+-----------------------------------
               dmark2html |    26  0.00s  0.02s  0.07s   0.65s
```

**Pull request merged**
