### PR TITLE
Add test task

### PR DESCRIPTION
**Pull request by ddfreyne**
This will allow us to hook up the nanoc web site to Travis CI.

### CODE REVIEW

**Comment by mpapis** [comment]
hmm, why not <https://github.com/rvm/rvm-site/blob/master/lib/tasks/compile.rake#L11>:
```ruby
Nanoc::CLI.run(%w[compile])
Nanoc::CLI.run(%w[check --deploy])
```

**Comment by ddfreyne** [comment]
The `sh` approach is simpler and people are already used to invoking `nanoc` on the command line.

**Comment by mpapis** [comment]
the code looks simpler, but the effect is executing shell, running nanoc and in the end running exactly the same code ;)

otherwise :+1:

**Comment by bobthecow** [comment]
:+1: `sh` works for me :)

**Pull request merged**
