### PR TITLE
Added Documentation for Deploying to GitLab pages

### PR DESCRIPTION
**Pull request by abuango**
I recently deployed my personal website (abuango.me) using Nanoc and GitLab Pages, I decided to make this PR to guide other users.

Great work!

### CODE REVIEW

**Comment by ddfreyne** [comment]
Whoa, this looks great! I do have a couple of changes that I’d like to make, but I’ll make them as separate commits after it’s merged into master.

**Comment by ddfreyne** [comment]
Hmm, so the GitLab setup is different from GitHub and Bitbucket. It uses GitLab’s CI to do the building on GitLab, whereas the GitHub/Bitbucket docs expect the output/ dir to be a Git repo that’s pushed.

While it’s good to document how to use GitLab CI with Nanoc, I think it needs to be more clear in how it’s different. I’m thinking about splitting the documentation in two parts:

* Deploying a pre-compiled static site
  * GitHub
  * BitBucket
  * GitLab (new)
* Setting up a CD pipeline to compile content (new)
  * GitLab
  * Travis CI + ???
  * CircleCI + ???

It’ll take a bit longer before I can merge this PR then though!

**Comment by ddfreyne** [comment]
FYI: I set up nanoc.gitlab.io with these instructions!

**Comment by ddfreyne** [comment]
See #208, which is the same as this PR with a few more changes (still WIP, though).

**Comment by abuango** [comment]
Nice, I guess we can close this in favor of #208.

**Pull request closed without merging**
