### PR TITLE
Support for docset

### PR DESCRIPTION
**Pull request by barraq**
This PR is about adding support for docset to Nanoc.

With tools like [Dash](https://kapeli.com/dash) or [Zeal](https://zealdocs.org) it would be really handy to have access to an offline Nanoc docset. This PR provides a basic Nanoc docset.

I would like to open discussion regarding possible enhancement of this docset by adding support for docset types, see: https://kapeli.com/docsets#supportedentrytypes. Such support would be really easy to do, they will however require to agree on some selectors.

@ddfreyne what do you think?

Best

### CODE REVIEW

**Comment by barraq** [comment]
Initial docset for Nanoc.ws 
[nanoc.ws.docset.zip](https://github.com/nanoc/nanoc.ws/files/95936/nanoc.ws.docset.zip)

**Comment by ddfreyne** [comment]
This looks quite interesting! There’s a few changes that I’d like to see:

* Reflect the ToC hierarchy if possible (probably means not just guides, but also references)
* Create a docset-specific style (without navigation, footer, sidebar)
* Remove `Nanoc >>` prefix from title
* Fix duplicate titles (_Helpers_ can be both part of guides and part of reference)
* Create separate entries for
  * helpers
  * filters
  * variables

**Comment by barraq** [comment]
Hey @ddfreyne I didn't forget you! I was really busy lately.
I noticed that you were updating the Nanoc website (in order to prepare a book right?), so I am taking some time to discuss the points you listed below.

In order to reflect ToC hierarchy, hide part of page (e.g. navigation, footer, sidebar, etc.), but also create separate entries for helpers, filters and variables we need to have specific selectors. If you look quickly at the doc for Dashing here https://github.com/technosophos/dashing#readme you will notice that you can associated selector to Docset entry types (https://kapeli.com/docsets#supportedentrytypes).

In your effort to update the website, can we also include adding better selectors (with classes and ids) so that we will be able to build an awesome Docset? How can I help you?

Thanks a lot @ddfreyne you are doing an amazing work!

**Comment by ddfreyne** [comment]
I’ve played around a bit with docset generation using dashing, and came up with something like this:

screen shot 2016-04-23 at 11 04 44

(See #170 for the `dashing.json` file)

I don’t I like this approach very much. dashing is very limited in what it can do, and I believe I’d rather generate the docset manually, which’ll give me the option to use a custom stylesheet that’s better fit for docsets.

**Comment by ddfreyne** [comment]
I’ll close this PR as it has been around for a while, inactive, and more thought needs to go into how to generate this automatically. I’ve created #182 to track ideas.

**Pull request closed without merging**
