### PR TITLE
Improve upgrade guide (identifiers / data sources)

### PR DESCRIPTION
**Pull request by th-h**
A first draft for (part of) #202.

(I'm not sure if I got the formatting right as I have no way to test DMark, and the language could be improved ...)

Signed-off-by: Thomas Hochstein <thh@inter.net>

### CODE REVIEW

**Comment by ddfreyne** [comment]
Take a look at 54a28444a0102017990cf59fb3e83fbd22484b38 — this replaces the need for the two notes you’ve added in the upgrade guide with an explicit sequence of steps on how to upgrade custom data sources:

screen shot 2017-08-22 at 22 58 23

**Comment by ddfreyne** [comment]
I’ve applied your `converted to an identifier` -> `converted to a full identifier` change on master!

**Comment by ddfreyne** [comment]
I _think_ that with the recent changes to nanoc.ws and the upcoming change to Nanoc that will prevent full identifiers from ending with a slash, this PR is now obsolete.

Thanks for getting the ball rolling!

**Comment by ddfreyne** [comment]
I’ll close the PR for now, but more changes are definitely welcome!

**Comment by th-h** [comment]
That looks very good, thank you very much!

**Pull request closed without merging**
