### PR TITLE
Next/previous links in documentation

### PR DESCRIPTION
**Pull request by ddfreyne**
Mostly just an idea I’m playing around with. This approach (probably in a different format) might make it easier to consume documentation and encourage reading.

Here’s what it looks like right, but this is not the way I want to keep it (note the logical navigation is totally wrong):

screen shot 2015-06-17 at 09 51 18

Perhaps prev/next links at the bottom of the page, or floating to the right (below the sidebar) might be useful.

### CODE REVIEW

**Comment by DaveEveritt** [comment]
I think: previous/next at bottom of item, all items or sections at-a-glance in a dropdown (or easily accesible) menu

**Comment by denis-soundcloud** [comment]
The [How to design programs](http://www.ccs.neu.edu/home/matthias/HtDP2e/part_one.html) site has navigation that is pretty much the way I wanted it. Inspiration!

**Comment by ddfreyne** [comment]
Improved:

screen shot 2015-06-28 at 15 52 57

**Comment by ddfreyne** [comment]
This also cleans up the ToC code on the main documentation page.

**Comment by DaveEveritt** [comment]
Perfect :-)

**Comment by bobthecow** [comment]
:+1:

**Pull request merged**
