### PR TITLE
Include example of a glob negation pattern

### PR DESCRIPTION
**Pull request by da2x**

### CODE REVIEW

**Comment by da2x** [comment]
Or maybe remove the examples and link to https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Pattern-Matching ?

**Comment by da2x** [comment]
Sorry. Forgot this only works in my version.

**Comment by ddfreyne** [comment]
Now you’ve got me curious — what _is_ your version? 😄

**Comment by da2x** [comment]
> what is your version?

A horrible patch that forks off a Bash process to run glob patterns not natively supported by Ruby. I looked at the docs for something else and noticed it was missing. Forgot it was just something I put together for myself.

**Pull request closed without merging**
