### PR TITLE
Add GitLab pages deploy documentation

### PR DESCRIPTION
**Pull request by ddfreyne**
This is based off @abuango’s #207, with minor modifications (in particular, moving the instructions to a new “With CI pipeline tools” section).

* [ ] Clean up commit history (squash?)
* [x] Integrate with `nanoc check --deploy`

### CODE REVIEW

**Comment by ddfreyne** [comment]
screen shot 2017-09-28 at 00 25 16

**Comment by ddfreyne** [comment]
And deployed: https://nanoc.ws/doc/deploying/#with-ci-pipeline-tools — thanks for the write-up!

**Comment by ddfreyne** [comment]
That was worth a tweet: https://twitter.com/nanoc_ssg/status/914781247460839424

**Comment by abuango** [comment]
Awesome, I also retweeted. I look forward to contributing more to nanoc.

**Pull request merged**
